module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'test',
        'transport-inmemory',
        'transport-rabbitmq',
        'transport-kafka',
        'transport-sqs',
        'transport-redis',
        'transport-nats',
        'transport-azure-servicebus',
        'transport-gcp-pubsub',
        'store-inmemory',
        'store-postgres',
        'store-mysql',
        'store-sqlserver',
        'store-mongo',
        'store-dynamodb',
        'store-redis',
        'store-sqlite',
        'store-prisma',
        'middleware-logging',
        'middleware-tracing',
        'middleware-metrics',
        'middleware-validation',
        'middleware-idempotency',
        'middleware-tenant',
        'nestjs',
        'nextjs',
        'express',
        'fastify',
        'hono',
        'deps',
        'ci',
        'release',
      ],
    ],
    'scope-empty': [1, 'never'],
  },
};
